import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Button from '@/components/Button'
import NextLogo from '../../../public/next.svg'
import CheckIcon from '../../../src/assets/svg/outline/action/check.svg';

export default function Home() {
  return (
    <>
      <Head>
        <title>Design System Components</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <Button>
            Button
          </Button>
          <Image
            src={CheckIcon}
            alt="Vercel Logo"
            className={styles.vercelLogo}
            width={24}
            height={24}
            priority
          />
        </div>
      </main>
    </>
  )
}
